# Generated by Django 3.2 on 2021-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=750)),
                ('year', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'ALL')], default=5)),
                ('dept', models.IntegerField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'EEE'), (4, 'IT'), (5, 'ECE'), (6, 'MECH'), (7, 'EIE'), (8, 'ALL')], default=8)),
                ('section', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'ALL')], default=4)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
