# Generated by Django 3.1.6 on 2021-02-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210220_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='content',
            field=models.TextField(max_length=750),
        ),
    ]
