# Generated by Django 3.2 on 2021-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Credit', max_length=50)),
                ('year', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1)),
                ('dept', models.IntegerField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'EEE'), (4, 'IT'), (5, 'ECE'), (6, 'MECH'), (7, 'EIE')], default=1)),
                ('sub', models.CharField(max_length=50, unique=True)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timetables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='TimeTable', max_length=50)),
                ('year', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1)),
                ('dept', models.IntegerField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'EEE'), (4, 'IT'), (5, 'ECE'), (6, 'MECH'), (7, 'EIE')], default=1)),
                ('section', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default=1)),
                ('timetable', models.ImageField(upload_to='timetable/')),
            ],
        ),
    ]
