# Generated by Django 3.1.6 on 2021-02-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='dept',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'EEE'), (4, 'IT'), (5, 'ECE'), (6, 'MECH'), (7, 'EIE')], default=1),
        ),
        migrations.AddField(
            model_name='credits',
            name='section',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default=1),
        ),
        migrations.AddField(
            model_name='credits',
            name='year',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1),
        ),
        migrations.AddField(
            model_name='timetables',
            name='dept',
            field=models.IntegerField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'EEE'), (4, 'IT'), (5, 'ECE'), (6, 'MECH'), (7, 'EIE')], default=1),
        ),
        migrations.AddField(
            model_name='timetables',
            name='section',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default=1),
        ),
        migrations.AddField(
            model_name='timetables',
            name='year',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1),
        ),
        migrations.AlterField(
            model_name='timetables',
            name='timetable',
            field=models.ImageField(upload_to='timetable/'),
        ),
    ]
