# Generated by Django 3.1.6 on 2021-02-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20210220_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='title',
            field=models.CharField(default='Credit', max_length=50),
        ),
        migrations.AddField(
            model_name='timetables',
            name='title',
            field=models.CharField(default='TimeTable', max_length=50),
        ),
    ]
