# Generated by Django 3.1.6 on 2021-02-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20210220_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='section',
        ),
    ]
