# Generated by Django 3.2 on 2021-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Delete')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
